Array norm
angelopolotto/scidart pull request #57
Opened 2023-02-01 09:12 UTC by saroad2

Calculate the norm of an array

2023-02-10 19:33 UTC, saroad2 commented
Hey @polotto, I would love your feedback on this 🙏

2023-12-01 19:17 UTC, polotto commented on lib/src/numdart/arrays_base/array_operations/array_norm.dart
> +/// print(arrayAddToScalar(list, 2));
The example is calling the wrong function name. Please, fix it.

2023-12-01 19:19 UTC, polotto requested changes

2023-12-01 19:19 UTC, polotto commented on lib/src/numdart/arrays_base/array_operations/array_norm.dart
> +/// print(arrayAddToScalar(list, 2));
You can use some test example.

2023-12-01 19:24 UTC, polotto approved these changes

2023-12-01 19:28 UTC, merged